#!/usr/bin/env bash
#  A Bash script that transfers a file from our client to a server
file_path=$1
ip=$2
username=$3
ssh_key=$4
count=0
if [[ $# < 3 || $# < 4 ]];then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit;
fi

sudo scp -i $ssh_key  $file_path "$username@$ip:/home/ubuntu"
