#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.html
echo "Hello World!" > /usr/share/nginx/www/index.html
echo "Hello World!" > /usr/share/nginx/html/index.html

service nginx start
