#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" >> index.html
sudo mv index.html /var/www/html/

sudo nginx -s reload
sudo service nginx start
