#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update
cd /etc/haproxy
sudo cp haproxy.cfg haproxy.cfg.orig
sudo chmod 777 haproxy.cfg
sudo printf "\n%s\n" "frontend haproxy-main
    bind *:80
    option forwardfor  
    default_backend nginx_webservers    

backend nginx_webservers
    balance roundrobin
    server websvr1	18.207.207.66:80 check
    server websvr2	54.90.27.97:80 check" >> haproxy.cfg
sudo chmod 644 haproxy.cfg
cd
sudo service haproxy restart
