#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update;
sudo apt-get -y install --no-install-recommends software-properties-common;
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6;
sudo apt-get -y install haproxy=2.6.\*;

echo "ENABLED=1" | sudo tee /etc/default/haproxy

echo -e "\nfrontend web_frontend\n\tbind *:80\n\tdefault_backend web_backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_backend\n\tbalance roundrobin\n\tserver web-01 18.207.207.66:80 check\n\tserver web-02 54.90.27.97:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
