#!/usr/bin/env bash
# Script displays numbers from 1 to 100
#	Displays 'FizzBuzz' when the number is a multiple of 3 and 5
#	Displays 'Fizz' when the number is a multiple of 3
# 	Displays 'Buzz' when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

i=1;
while ((i <= 100));do
	output=""
	if ((i % 3 == 0));then
		output+="Fizz"
	fi
	if ((i % 5 == 0)); then
		output+="Buzz"
	fi

	if [[ -z $output ]];then
		echo "$i" 
	else
		printf "%s\n" $output
	fi
	((i++))
done
