#!/usr/bin/env bash
# Script displays the content of the file '/etc/passwd'
# Script only displays:
#	username
#	user id
#	Home directory path for the user

while read -r line;do
	echo "$line" | cut -d : -f 2,4,5,7 --complement;
done < /etc/passwd
