#!/usr/bin/env bash
# Script displays the content of the '/etc/passwd' using 'while' loop + IFS

while IFS=:, read -r q1 q2 q3 q4 q5 q6 q7;do
	echo "The user $q1 is part of the $q4 gang, lives in $q6 and rides $q7. $q3's place is protected by the passcode $q2, more info about the user here: $q5";
done < /etc/passwd
