#!/usr/bin/env bash
# Script displays the time for 12hours and 59 minutes
# 	display hours from 0 to 12
# 	display minutes from 1 to 59

h=0
while ((h <= 12)); do
	m=1
	echo "Hour: $h"
	while ((m <= 59));do
		echo $m
		((m++));
	done
	((h++));
done

