#!/usr/bin/env bash
# Script displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed

names=$(ls);
for name in $names;do
	echo "$name";
done
