#!/usr/bin/env bash
# Script gives information about the 'school' file.
# If file exists:
# 	print 'school file exists'
#	If the file is empty:
#		print 'school file is empty'
#	If the file is not empty:
#		print 'school file is not empty'
#	If the file is a regular file:
#		print 'school is a regular file'
# Else:
#	print 'school file does not exist'

if [ -e 'school' ];then
	echo "school file exists";
	if [ -f 'school' ];then
		strs=$(cat school);
		if [[ $strs == '' ]];then
			echo "school file is empty"
		else
			echo "school file is not empty"
		fi
		echo "school is a regular file";
	else
		echo "school file is not empty"
	fi
else
	echo "school file does not exist"
fi
