#!/usr/bin/env bash
# Script changes the home IP address and also changes the IP address of facebook.com on this machine
sed s/127.0.0.1/127.0.0.2/ /etc/hosts > ~/hosts
echo "8.8.8.8		facebook.com" | cat >> ~/hosts
sudo cp -f ~/hosts /etc/hosts
rm ~/hosts
