#!/usr/bin/env bash
# Script displays all active IPv4 IPs on the machine it's executed on.
ifconfig | grep -oE "inet [0-9]*\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | grep -oE "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | cat
